"""empty message

Revision ID: da6976119610
Revises: 
Create Date: 2021-09-22 10:31:55.711475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6976119610'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=30), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('telefone_secundario', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=500), nullable=False),
    sa.Column('bairro', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=200), nullable=False),
    sa.Column('cep', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('gestor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=30), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('telefone_secundario', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=500), nullable=False),
    sa.Column('bairro', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=200), nullable=False),
    sa.Column('cep', sa.String(length=50), nullable=False),
    sa.Column('confirmacao_cadastro', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.LargeBinary(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lawyer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=30), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('telefone_secundario', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=500), nullable=False),
    sa.Column('bairro', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=200), nullable=False),
    sa.Column('cep', sa.String(length=50), nullable=False),
    sa.Column('confirmacao_cadastro', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.LargeBinary(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('medico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('especialidade', sa.String(length=100), nullable=False),
    sa.Column('sexo', sa.String(length=30), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('foto_perfil', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('facebook', sa.String(length=100), nullable=True),
    sa.Column('twitter', sa.String(length=100), nullable=True),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.Column('cpf', sa.String(length=30), nullable=False),
    sa.Column('rg', sa.String(length=30), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('telefone_secundario', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=500), nullable=False),
    sa.Column('bairro', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=200), nullable=False),
    sa.Column('cep', sa.String(length=50), nullable=False),
    sa.Column('confirmacao_cadastro', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.LargeBinary(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rg')
    )
    op.create_table('outros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=30), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('telefone_secundario', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=500), nullable=False),
    sa.Column('bairro', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=200), nullable=False),
    sa.Column('cep', sa.String(length=50), nullable=False),
    sa.Column('confirmacao_cadastro', sa.Boolean(), nullable=True),
    sa.Column('permissao_adm', sa.Boolean(), nullable=True),
    sa.Column('nivel_permissao', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.LargeBinary(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('responsavel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=30), nullable=False),
    sa.Column('rg', sa.String(length=30), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('telefone_secundario', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=500), nullable=False),
    sa.Column('bairro', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=200), nullable=False),
    sa.Column('cep', sa.String(length=50), nullable=False),
    sa.Column('confirmacao_cadastro', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.LargeBinary(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rg')
    )
    op.create_table('anotacoesmedico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=1000), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['medico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_adm_gestor',
    sa.Column('administrador_id', sa.Integer(), nullable=True),
    sa.Column('gestor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrador_id'], ['administrador.id'], ),
    sa.ForeignKeyConstraint(['gestor_id'], ['gestor.id'], )
    )
    op.create_table('association_adm_lawyer',
    sa.Column('administrador_id', sa.Integer(), nullable=True),
    sa.Column('lawyer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrador_id'], ['administrador.id'], ),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyer.id'], )
    )
    op.create_table('association_adm_medico',
    sa.Column('administrador_id', sa.Integer(), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrador_id'], ['administrador.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medico.id'], )
    )
    op.create_table('association_adm_outros',
    sa.Column('administrador_id', sa.Integer(), nullable=True),
    sa.Column('outros_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrador_id'], ['administrador.id'], ),
    sa.ForeignKeyConstraint(['outros_id'], ['outros.id'], )
    )
    op.create_table('horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['medico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('cpf', sa.String(length=30), nullable=False),
    sa.Column('rg', sa.String(length=30), nullable=False),
    sa.Column('documentos_pessoais', sa.String(length=2000), nullable=False),
    sa.Column('diagnostico', sa.String(length=2000), nullable=False),
    sa.Column('laudo_medico', sa.String(length=2000), nullable=False),
    sa.Column('receita_medica', sa.String(length=2000), nullable=False),
    sa.Column('endereco', sa.String(length=500), nullable=False),
    sa.Column('bairro', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=200), nullable=False),
    sa.Column('cep', sa.String(length=50), nullable=False),
    sa.Column('permissao_calendario', sa.Boolean(), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('outros_id', sa.Integer(), nullable=True),
    sa.Column('lawyer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyer.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['outros_id'], ['outros.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsavel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('rg')
    )
    op.create_table('agendamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('administrador_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['administrador_id'], ['administrador.id'], ),
    sa.ForeignKeyConstraint(['horario_id'], ['horario.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_adm_patient',
    sa.Column('administrador_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrador_id'], ['administrador.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], )
    )
    op.create_table('ssociation_gestor_patient',
    sa.Column('gestor_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gestor_id'], ['gestor.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ssociation_gestor_patient')
    op.drop_table('association_adm_patient')
    op.drop_table('agendamento')
    op.drop_table('patient')
    op.drop_table('horario')
    op.drop_table('association_adm_outros')
    op.drop_table('association_adm_medico')
    op.drop_table('association_adm_lawyer')
    op.drop_table('association_adm_gestor')
    op.drop_table('anotacoesmedico')
    op.drop_table('responsavel')
    op.drop_table('outros')
    op.drop_table('medico')
    op.drop_table('lawyer')
    op.drop_table('gestor')
    op.drop_table('administrador')
    # ### end Alembic commands ###
