"""empty message

Revision ID: e064863d9d15
Revises: 
Create Date: 2021-05-07 17:16:44.912946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e064863d9d15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=30), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('telefone_secundario', sa.String(length=20), nullable=True),
    sa.Column('endereço', sa.String(length=500), nullable=False),
    sa.Column('bairro', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=200), nullable=False),
    sa.Column('cep', sa.String(length=50), nullable=False),
    sa.Column('nome_associação', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('gestor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=30), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('telefone_secundario', sa.String(length=20), nullable=True),
    sa.Column('endereço', sa.String(length=500), nullable=False),
    sa.Column('bairro', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=200), nullable=False),
    sa.Column('cep', sa.String(length=50), nullable=False),
    sa.Column('nome_associação', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('medico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('especialidade', sa.String(length=100), nullable=False),
    sa.Column('sexo', sa.String(length=2000), nullable=True),
    sa.Column('Bio', sa.String(length=100), nullable=True),
    sa.Column('foto_perfil', sa.String(length=2000), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('facebook', sa.String(length=100), nullable=True),
    sa.Column('twitter', sa.String(length=100), nullable=True),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.Column('cpf', sa.String(length=30), nullable=False),
    sa.Column('rg', sa.String(length=30), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('telefone_secundario', sa.String(length=20), nullable=True),
    sa.Column('endereço', sa.String(length=500), nullable=False),
    sa.Column('bairro', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=200), nullable=False),
    sa.Column('cep', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rg')
    )
    op.create_table('outros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=30), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('telefone_secundario', sa.String(length=20), nullable=True),
    sa.Column('endereço', sa.String(length=500), nullable=False),
    sa.Column('bairro', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=200), nullable=False),
    sa.Column('cep', sa.String(length=50), nullable=False),
    sa.Column('nome_associação', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('responsavel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('telefone_secundario', sa.String(length=20), nullable=True),
    sa.Column('endereço', sa.String(length=500), nullable=False),
    sa.Column('bairro', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('association',
    sa.Column('administrador', sa.Integer(), nullable=True),
    sa.Column('gestor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrador'], ['administrador.id'], ),
    sa.ForeignKeyConstraint(['gestor'], ['gestor.id'], )
    )
    op.create_table('association3',
    sa.Column('administrador', sa.Integer(), nullable=True),
    sa.Column('medico', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrador'], ['administrador.id'], ),
    sa.ForeignKeyConstraint(['medico'], ['medico.id'], )
    )
    op.create_table('association4',
    sa.Column('administrador', sa.Integer(), nullable=True),
    sa.Column('outros', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrador'], ['administrador.id'], ),
    sa.ForeignKeyConstraint(['outros'], ['outros.id'], )
    )
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=30), nullable=False),
    sa.Column('rg', sa.String(length=30), nullable=False),
    sa.Column('documentos_pessoais', sa.String(length=2000), nullable=False),
    sa.Column('diagnóstico', sa.String(length=2000), nullable=False),
    sa.Column('laudo_médico', sa.String(length=2000), nullable=False),
    sa.Column('receita_médica', sa.String(length=2000), nullable=False),
    sa.Column('endereço', sa.String(length=500), nullable=False),
    sa.Column('bairro', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(length=128), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('outros_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['outros_id'], ['outros.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsavel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rg')
    )
    op.create_table('advogado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=30), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('telefone_secundario', sa.String(length=20), nullable=True),
    sa.Column('endereço', sa.String(length=500), nullable=False),
    sa.Column('bairro', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=200), nullable=False),
    sa.Column('cep', sa.String(length=50), nullable=False),
    sa.Column('nome_associação', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(length=128), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('association2',
    sa.Column('administrador', sa.Integer(), nullable=True),
    sa.Column('paciente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrador'], ['administrador.id'], ),
    sa.ForeignKeyConstraint(['paciente'], ['paciente.id'], )
    )
    op.create_table('association5',
    sa.Column('gestor', sa.Integer(), nullable=True),
    sa.Column('paciente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gestor'], ['gestor.id'], ),
    sa.ForeignKeyConstraint(['paciente'], ['paciente.id'], )
    )
    op.create_table('association6',
    sa.Column('administrador', sa.Integer(), nullable=True),
    sa.Column('advogado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrador'], ['administrador.id'], ),
    sa.ForeignKeyConstraint(['advogado'], ['advogado.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association6')
    op.drop_table('association5')
    op.drop_table('association2')
    op.drop_table('advogado')
    op.drop_table('paciente')
    op.drop_table('association4')
    op.drop_table('association3')
    op.drop_table('association')
    op.drop_table('responsavel')
    op.drop_table('outros')
    op.drop_table('medico')
    op.drop_table('gestor')
    op.drop_table('administrador')
    # ### end Alembic commands ###
